--- ### 代码生成器配置
generator:
  # 排除数据表
  excludeTables:
    - DATABASECHANGELOG
    - DATABASECHANGELOGLOCK
    - gen_config
    - gen_field_config
  ## 类型映射
  typeMappings:
    MYSQL:
      String:
        - varchar
        - char
        - text
        - mediumtext
        - longtext
        - tinytext
        - json
      Integer:
        - int
        - tinyint
        - smallint
        - mediumint
        - integer
      Long:
        - bigint
      Float:
        - float
      Double:
        - double
      Boolean:
        - bit
      BigDecimal:
        - decimal
      LocalDate:
        - date
      LocalDateTime:
        - datetime
        - timestamp
    POSTGRE_SQL:
      String:
        - varchar
        - char
        - text
        - json
      Integer:
        - int2
        - int4
      Long:
        - int8
      Float:
        - float4
      Double:
        - float8
      Boolean:
        - bool
      BigDecimal:
        - decimal
      LocalDate:
        - date
      LocalDateTime:
        - timestamp
  ## 模板配置
  templateConfigs:
    DO:
      # 模板路径
      templatePath: vben/backend/Entity.ftl
      # 包名称
      packageName: model.entity
      # 排除字段
      excludeFields:
        - id
        - createUser
        - createTime
        - updateUser
        - updateTime
    Query:
      templatePath: vben/backend/Query.ftl
      packageName: model.query
    Req:
      templatePath: vben/backend/Req.ftl
      packageName: model.req
    Resp:
      templatePath: vben/backend/Resp.ftl
      packageName: model.resp
      excludeFields:
        - id
        - createUser
        - createTime
    DetailResp:
      templatePath: vben/backend/DetailResp.ftl
      packageName: model.resp
      excludeFields:
        - id
        - createUser
        - createTime
        - updateUser
        - updateTime
    Mapper:
      templatePath: vben/backend/Mapper.ftl
      packageName: mapper
    MapperXml:
      templatePath: vben/backend/MapperXml.ftl
      packageName: mapper
      extension: .xml
      suffix: Mapper
    Service:
      templatePath: vben/backend/Service.ftl
      packageName: service
    ServiceImpl:
      templatePath: vben/backend/ServiceImpl.ftl
      packageName: service.impl
    Controller:
      templatePath: vben/backend/Controller.ftl
      packageName: controller
    api:
      templatePath: vben/frontend/api.ftl
      packageName: src/api # 此处arco 路径是src/apis
      extension: .ts
      backend: false
    index:
      templatePath: vben/frontend/index.ftl
      packageName: src/views
      extension: .vue
      backend: false
    AddModal:
      templatePath: vben/frontend/AddModal.ftl
      packageName: src/views
      extension: .vue
      backend: false
    DetailDrawer:
      templatePath: vben/frontend/DetailDrawer.ftl
      packageName: src/views
      extension: .vue
      backend: false
    Menu:
      template-path: vben/backend/Menu.ftl
      packageName: sql
      extension: .sql
      backend: true
    Data:
      templatePath: vben/frontend/data.ftl
      packageName: src/views
      extension: .ts
      backend: false
    zh-CN:
      template-path: vben/frontend/zh-CN.ftl
      packageName: src/locales/langs/zh-CN
      extension: .json
      backend: false
    en-US:
      template-path: vben/frontend/en-US.ftl
      packageName: src/locales/langs/en-US
      extension: .json
      backend: false
    EditDrawer:
      templatePath: vben/frontend/EditDrawer.ftl
      packageName: src/views
      extension: .vue
      backend: false
    EditModal:
      templatePath: vben/frontend/EditModal.ftl
      packageName: src/views
      extension: .vue
      backend: false